# Generated by Django 3.1.2 on 2021-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('authors', models.CharField(max_length=180)),
                ('cover', models.ImageField(upload_to='')),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
