# Generated by Django 3.1.2 on 2021-04-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20210323_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_type',
        ),
    ]
